# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
      # Runs a set of commands using the runners shell
      - name: Upgrade pip
         run: |
            pip install --upgrade pip
            
      - name: Set up AWS Environment
        run: |
          pip install awscli
          pip install python-lambda
          aws configure set region us-east-1 --profile default
          aws configure set aws_access_key_id ${{ secrets.PRIMARY_AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.PRIMARY_AWS_SECRET_ACCESS_KEY }} --profile default
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      -name: Test
        run: |  
          pip install pytest
          pytest -v
          
      - name: Deploy
        run: |
          # using `python-lambda`
          lambda deploy
